fiber_amie/api/urls.py
from django.urls import path, include
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'yarns', views.AddYarnViewSet)
router.register(r'hooks', views.AddHookViewSet)
router.register(r'needles', views.AddNeedleViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'projects_drf', views.AddProjectViewSet)
router.register(r'counters', views.CounterViewSet)



urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

fiber_amie/app_users/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = 'app_users'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('sign_up/', views.sign_up_request, name='sign-up'),
    path('login/', views.login_request, name='log-in'),
    path('logout/', views.logout_request, name='logout'),
    path('settings/', views.settings, name='settings'),
]

fiber_amie/fiber_amie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework import routers
from api import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_users.urls')),
    path('', include('app_data.urls')),
    path('', include('api.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='app'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# router = routers.DefaultRouter()
# router.register(r'yarn', views.AddYarnViewSet)
# router.register(r'hooks', views.AddHookViewSet)
# router.register(r'needles', views.AddNeedleViewSet)

# urlpatterns = [
#     path('', include(router.urls)),
#     path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
# ]

fiber_amie/app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')
        
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        # if self.cleaned_data['password1'] == self.cleaned_data['password2']:
        #     user.password = self.cleaned_data['password1']
        if commit:
            user.save()
        return user

fiber_amie/app_users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

from .forms import NewUserForm

# USERS ------------------------------- #

def index(request):
    form = NewUserForm()
    form2 = AuthenticationForm()
    return render(request, 'app_users/index.html', context={'sign_up_form':form, 'login_form':form2})
    # return redirect('app_users:home', context={'sign_up_form':form, 'login_form':form2})

def home(request):
    ...
    return render(request, 'app_users/home.html')

def settings(request):
    ...
    return render(request, 'app_users/settings.html')

# sign up 
def sign_up_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        print(form.errors)
        # print(form, request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user) # logs user in automatically if sign up is successful
            messages.success(request, 'You\'ve registered successfully!')
            return redirect('app_users:home') # sends user back to home page
        messages.error(request, 'Oops! Something went wrong.')
    form = NewUserForm()
    return render(request=request, template_name='app_users/index.html', context={'sign_up_form':form})

# log in 
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None: # aka if user is registered
                login(request, user) # log user in
                messages.info(request, f'Welcome, {username}!')
                return redirect('app_users:home')
            else:
                messages.error(request, 'Please double check your username or password.')
        else: 
            messages.error(request, 'Please double check your username or password.')
    form = AuthenticationForm()
    return render(request=request, template_name='app_users/index.html', context={'login_form':form})

# log out 
def logout_request(request):
    logout(request)
    messages.info(request, 'You\'ve been logged out!')
    return redirect('app_users:index')

fiber_amie/app_users/templates/app_users/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fiber Amie</title>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/vue@3"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">


    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">

</head>
<style src="{% static 'base.css' %}"></style>
<!-- <style>
@media screen and (min-width: 360px) {
    .landing {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    .landing > h1 {
        font-family: 'Berkshire Swash', cursive;
        font-size: 5rem;
        color: #896283;
        text-shadow: 1px 1px #383838;
        margin-bottom: -2rem;
        margin-top: -.5rem;
    }
    .landing > h1 > #color {
        color: #383838;
        text-shadow: 1px 1px #896283;
    }
    .landing h4 {
        font-family: 'Raleway', sans-serif;
        font-weight: 300;
        font-size: 1.5rem;
    }
    .landing p {
        font-family: 'Raleway', sans-serif;
        font-size: 1.5rem;
        margin-right: 2rem;
        margin-left: 2rem;
        text-align: center;
    }
    .landing > .button {
        background-color: #896283;
        color: #fff;
        padding: 1rem;
        padding-right: 2rem;
        padding-left: 2rem;
        margin: .75rem;
        font-family: 'Raleway', sans-serif;
        font-size: 2rem;
        font-weight: 600;
        border: 1px solid #896283;
        border-radius: 30px;
    }
}
    
</style> -->
{% block content %}
<style src="{% static 'base.css' %}"></style>

<body>
    <div class="wrapper" id="app">


    </div>
    <script src="{% static 'script.js' %}"></script>
    {% endblock %}
</body>

</html>

fiber_amie/app_users/templates/app_users/home.html
{% extends 'app_users/base_layout.html' %}
{% load static %}

<!-- HOME PAGE ------------------------------- -->
{% block content %}
<link href="{% static 'css/home.css' %}" rel="stylesheet">

<div class="home" id="app">

    <div class="topnav">
        <img @click="showMenu = true" id="settings-mobile" src="{% static 'images/settings.svg' %}">
        <div class="menu-overlay" v-if="showMenu" @click="showMenu = false"></div>
        <div class="modal" v-show="showMenu">
            {% csrf_token %}
            <a href="/settings" id="settings">Settings</a><br>
            <a href="/logout/">Log Out</a>
        </div>
        <!-- <img id="logo" src="{% static 'images/text-logo.png' %}"> -->
        <h1><i>fiber amie</i></h1>
        <img id="mini-logo" src="{% static 'images/fiber-amie-icon.png' %}">
    </div>





    {% if user.is_authenticated %}
    <div class="home-body">
        <p>Hi, {{ user.username }}, welcome to Fiber Amie!</p>
        <div class="app-info">
            <p>
                <i>Latest updates:</i><br>
            </p>
            <ul>
                <li>added row counter - add a "new counter" to start</li>
                <li>implemented edit button to project and stash items</li>
            </ul>
        </div>
        <!-- <p>Your recent projects...</p> -->
        <!-- <div class="project-list">
            <div class="project-card" v-for="project in projects">
                <p><b>[[ project.pattern_name ]]</b> by [[ project.designer ]]
                </p><br>
                <div class="project-image">
                    <img class="cover" :src="[[ project.image ]]"><br>
                </div>
                
                
            </div>
        </div> -->
    </div>



    {% endif %}

    <div class="navbar">
        <div class="home-icon">
            <a href="/home">
                <img src="{% static 'images/homeactive.svg' %}">
                <p id="nav-text">Home</p>
            </a>
        </div>
        <div class="icon">
            <a href="/counter">
                <img src="{% static 'images/counter.svg' %}">
                <p id="nav-text">Counter</p>
            </a>
        </div>
        <div class="icon">
            <a href="/projects">
                <img src="{% static 'images/projects.svg' %}">
                <p id="nav-text">Projects</p>
            </a>
        </div>
        <div class="icon">
            <a href="/stash">
                <img src="{% static 'images/stash.svg' %}">
                <p id="nav-text">Stash</p>
            </a>
        </div>
        <div class="icon">
            <a href="/tools">
                <img src="{% static 'images/tools.svg' %}">
                <p id="nav-text">Tools</p>
            </a>
        </div>
        <div class="icon" id="settings-desktop">
            <a href="/settings">
                <img src="{% static 'images/settings.svg' %}">
                <p id="nav-text">Settings</p>
            </a>
        </div>
    </div>
    <div class="footer">
        <div class="footer-contents">
            <p>FiberAmie &copy; 2022</p>
        </div>
    </div>
</div>
<!-- <script>
    document.querySelector(".sidenav-toggle").addEventListener("click", () => {
        document.querySelector(".wrapper").classList.toggle("side-nav-open");
    })
</script> -->
<script src="{% static 'js/projects.js' %}"></script>
{% endblock %}

fiber_amie/app_users/templates/app_users/index.html
{% extends 'app_users/base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- LANDING -------------------------  -->
<link href="{% static 'css/index.css' %}" rel="stylesheet">
<!-- <img src="app_users/text-logo.png"> -->
<div class="landing" id="app">
    <img id="logo" src="{% static 'images/text-logo.png' %}">
    <p>A mobile-friendly, accessible fiber companion app - keep track of your yarn stash, crochet hooks & knitting
        needles, and the projects you're working on - easily, and on the go!</p>


    <!-- SIGN UP -->
    <button class="button" @click="showSignUp = true">
        Sign Up
    </button>
    <div class="modal-overlay" v-if="showSignUp" @click="showSignUp = false"></div>
    <div class="form-modal" v-show="showSignUp">
        <form method="POST" action="{% url 'app_users:sign-up' %}">
            {% csrf_token %}
            <h1>sign up</h1>
            <!-- {{ sign_up_form|crispy }} -->
            <label>First name: </label><br>
            {{ sign_up_form.first_name }}<br>
            <label>Last name: </label><br>
            {{ sign_up_form.last_name }}<br>
            <label>Username: </label><br>
            {{ sign_up_form.username }}<br>
            <label>Email: </label><br>
            {{ sign_up_form.email }}<br>
            <label>Password: </label><br>
            {{ sign_up_form.password1 }}<br>
            <label>Confirm password: </label><br>
            {{ sign_up_form.password2 }}<br>
            <button type="submit" @click="showSignUp = false">Sign Up</button>
        </form>
    </div>

    <!-- LOG IN  -->
    <button class="button" @click="showLogIn = true">
        Log In
    </button>
    <div class="modal-overlay" v-if="showLogIn" @click="showLogIn = false"></div>
    <div class="form-modal" v-show="showLogIn">
        <div class="login-form-container">
            <form method="POST" action="{% url 'app_users:log-in' %}">
                <h1>log in</h1>
                {% csrf_token %}
                <div class="login-form">
                    <label>Username:</label><br>
                    {{ login_form.username }}
                </div><br>
                <div class="login-form">
                    <label>Password:</label><br>
                    {{ login_form.password }}
                </div><br>
                    <button type="submit" @click="showLogIn = false">Log In</button>
            </form>
        </div>
    </div>


</div>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

fiber_amie/app_users/templates/app_users/login.html
{% extends 'app_users/base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!--LOGIN -------------------------  -->
<link href="{% static 'css/login.css' %}" rel="stylesheet">

<div class="login" id="app">
    <h1><i>Log In</i></h1>
    <div class="login-form-container">
        <form method="POST">
            {% csrf_token %}
            <div class="login-form">
                <label>Username:</label><br>
                {{ login_form.username }}
            </div><br>
            <div class="login-form">
                <label>Password:</label><br>
                {{ login_form.password }}
            </div><br>

            <!-- {{ login_form|crispy }} -->
            
            <button type="submit">Submit</button>
            
        </form>
    </div>
</div>
<!-- <script src="{% static 'script.js' %}"></script> -->
{% endblock %}

fiber_amie/app_users/templates/app_users/settings.html
{% extends 'app_users/base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!--SETTINGS -------------------------  -->
<link href="{% static 'css/settings.css' %}" rel="stylesheet">

<div class="settings" id="app">
    <h1><i>settings</i></h1>
    <div id="logout">
        <a href="/logout/">Log Out</a>
    </div>

    <div class="settings-container">
        <h4>Theme Options</h4><br>
        <div class="settings-inner">
            <input type="checkbox" name="high-contrast" value="high-contrast">
            <label for="high-constrast">High constrast</label><br>
        </div>
        <div class="settings-inner">
            <input type="checkbox" name="low-contrast" value="low-contrast" checked>
            <label for="low-contrast">Low constrast</label><br><br>
        </div>
        <div class="settings-inner">
            <input type="checkbox" name="purple" value="purple" checked>
            <label for="purple">Purple/pink</label><br>
        </div>
        <div class="settings-inner">
            <input type="checkbox" name="sage" value="sage">
            <label for="sage">Sage/green</label><br><br>
        </div>
        <div class="settings-inner">
            <input type="checkbox" name="standard" value="standard" checked>
            <label for="standard">Standard font size</label><br>
        </div>
        <div class="settings-inner">
            <input type="checkbox" name="large" value="large">
            <label for="large">Large font size</label><br>
        </div>

        <h4>About</h4>
        <p>
            Fiber Amie was created because there is a gap in the knitting and crochet market for a mobile-friendly, accessible craft companion app. <br><br>
            Fiber Amie version 1.0<br>
            Created by Aimee Young &copy; 2022
        </p>
    </div>


    <div class="navbar">
        <div class="icon">
            <a href="/home">
                <img src="{% static 'images/home.svg' %}">
                <p id="nav-text">Home</p>
            </a>
        </div>
        <div class="icon">
            <a href="/counter">
                <img src="{% static 'images/counter.svg' %}">
                <p id="nav-text">Counter</p>
            </a>
        </div>
        <div class="icon">
            <a href="/projects">
                <img src="{% static 'images/projects.svg' %}">
                <p id="nav-text">Projects</p>
            </a>
        </div>
        <div class="icon">
            <a href="/stash">
                <img src="{% static 'images/stash.svg' %}">
                <p id="nav-text">Stash</p>
            </a>
        </div>
        <div class="icon">
            <a href="/tools">
                <img src="{% static 'images/tools.svg' %}">
                <p id="nav-text">Tools</p>
            </a>
        </div>
        <div class="settings-icon" id="settings-desktop">
            <a href="/settings">
                <img src="{% static 'images/settingsactive.svg' %}">
                <p id="nav-text">Settings</p>
            </a>
        </div>
    </div>
</div>
<script src="{% static 'js/settings.js' %}"></script>
{% endblock %}

fiber_amie/app_users/templates/app_users/signup.html
{% extends 'app_users/base_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!-- SIGN UP -------------------------  -->
<link href="{% static 'css/signup.css' %}" rel="stylesheet">

<div class="signup" id="app">
    {% csrf_token %}
    
    <form method="POST">
        {% csrf_token %}
        {{ sign_up_form|crispy }}
        <button type="submit" v-model="signUp">Sign Up</button>
    </form>
    
    <a href="#">Go back</a>
</div>
<script src="{% static 'script.js' %}"></script>
{% endblock %}